sliders_config:
  N: 
    min: 100
    max: 10000
    step: 10
    value: 1000
    description: "N"
  n_a:
    min: 0.1
    max: 0.9
    step: 0.1
    value: 0.5
    description: "n_a"
  alpha_a:
    min: 0.1
    max: 0.9
    step: 0.1
    value: 0.5
    description: "alpha_a"
  alpha_b:
    min: 0.0
    max: 1.0
    step: 0.01
    value: 0.5
    description: "alpha_b"
  mean_A0:
    min: -10
    max: 10
    step: 0.1
    value: -2
    description: "mean_A0"
  mean_B0:
    min: -10
    max: 10
    step: 0.1
    value: -6
    description: "mean_B0"
  mean_A1:
    min: -10
    max: 10
    step: 0.1
    value: 6
    description: "mean_A1"
  mean_B1:
    min: -10
    max: 10
    step: 0.1
    value: 2
    description: "mean_B1"
  std_A0:
    min: 0.1
    max: 3
    step: 0.1
    value: 1
    description: "std_A0"
  std_B0:
    min: 0.1
    max: 3
    step: 0.1
    value: 1
    description: "std_B0"
  std_A1:
    min: 0.1
    max: 3
    step: 0.1
    value: 1
    description: "std_A1"
  std_B1:
    min: 0.1
    max: 3
    step: 0.1
    value: 1
    description: "std_B1"
  st_epochs:
    min: 10
    max: 2000
    step: 10
    value: 200
    description: "st_epochs"
  st_lr:
    min: 0.01
    max: 1.0
    step: 0.01
    value: 0.2
    description: "st_lr"
  fed_epochs:
    min: 1
    max: 2000
    step: 1
    value: 1
    description: "fed_epochs"
  fed_lr:
    min: 0.01
    max: 1.0
    step: 0.01
    value: 0.1
    description: "fed_lr"

layout_groups:
  - ["N", "n_a"]
  - ["alpha_a", "alpha_b"]
  - ["mean_A0", "mean_B0"]
  - ["mean_A1", "mean_B1"]
  - ["std_A0", "std_B0"]
  - ["std_A1", "std_B1"]
  - ["st_epochs", "st_lr"]
  - ["fed_epochs", "fed_lr"]
